spring:
  application:
    name: JavaFlavors
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/javaflavors-api}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        validator:
          apply_to_ddl: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:https://auth.wfis.lol/application/o/javaflavors/}
          jwk-set-uri: ${OIDC_JWKS_URI:https://auth.wfis.lol/application/o/javaflavors/jwks/}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        security: INFO
