x-pg-db-credentials: &pg-db-credentials
  POSTGRES_USER: ${DB_USER:-postgres}
  POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
  POSTGRES_DB: ${DB_NAME:-java_flavors}


services:
  postgres:
    image: 'postgres:latest'
    environment:
      <<: *pg-db-credentials
    ports:
      - 5432:5432
    volumes:
      - device-manager-front-db-data:/var/lib/postgresql/data

volumes:
  device-manager-front-db-data:
