x-pg-db-credentials: &pg-db-credentials
  POSTGRES_USER: ${DB_USER:-postgres}
  POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
  POSTGRES_DB: ${DB_NAME:-javaflavors-front}

services:
  postgres:
    image: postgres:latest
    environment:
      <<: *pg-db-credentials
    ports:
      - ${DB_PORT:-7000}:5432
    volumes:
      - javaflavors-front-db-data:/var/lib/postgresql/data

volumes:
  javaflavors-front-db-data:
